
--D_Contact
INSERT INTO D_Contact(IdContact,NomContact,PrenomContact,MailContact,TelContact,IdFonction,MpContact) VALUES (1,'BERNARD CHAUSSEE','Léo-pol','leopol.bernard@gmail.com','6',1,'NULL');
INSERT INTO D_Contact(IdContact,NomContact,PrenomContact,MailContact,TelContact,IdFonction,MpContact) VALUES (2,'DUMAIS','Guy','guy.dumais@omnesports.fr','+33 01 23 45 67 89',2,'NULL');



--p_Pays
Insert Into p_Pays (Idpays,NomPays) values (1,'France');
Insert Into p_Pays (Idpays,NomPays) values (2,'Andorre');
Insert Into p_Pays (Idpays,NomPays) values (3,'Émirats arabes unis');
Insert Into p_Pays (Idpays,NomPays) values (4,'Afghanistan');
Insert Into p_Pays (Idpays,NomPays) values (5,'Antigua-et-Barbuda');
Insert Into p_Pays (Idpays,NomPays) values (6,'Anguilla');
Insert Into p_Pays (Idpays,NomPays) values (7,'Albanie');
Insert Into p_Pays (Idpays,NomPays) values (8,'Arménie');
Insert Into p_Pays (Idpays,NomPays) values (9,'Antilles néerlandaises');
Insert Into p_Pays (Idpays,NomPays) values (10,'Antarctique');
Insert Into p_Pays (Idpays,NomPays) values (11,'Argentine');
Insert Into p_Pays (Idpays,NomPays) values (12,'Samoa américaine');
Insert Into p_Pays (Idpays,NomPays) values (13,'Autriche');
Insert Into p_Pays (Idpays,NomPays) values (14,'Australie');
Insert Into p_Pays (Idpays,NomPays) values (15,'Aruba');
Insert Into p_Pays (Idpays,NomPays) values (16,'Azerbaïdjan');
Insert Into p_Pays (Idpays,NomPays) values (17,'Bosnie-Herzégowine');
Insert Into p_Pays (Idpays,NomPays) values (18,'Barbade');
Insert Into p_Pays (Idpays,NomPays) values (19,'Bangladesh');
Insert Into p_Pays (Idpays,NomPays) values (20,'Belgique');
Insert Into p_Pays (Idpays,NomPays) values (21,'Bulgarie');
Insert Into p_Pays (Idpays,NomPays) values (22,'Bahreïn');
Insert Into p_Pays (Idpays,NomPays) values (23,'Bermudes');
Insert Into p_Pays (Idpays,NomPays) values (24,'Brunéi Darussalam');
Insert Into p_Pays (Idpays,NomPays) values (25,'Bolivie');
Insert Into p_Pays (Idpays,NomPays) values (26,'Brésuk');
Insert Into p_Pays (Idpays,NomPays) values (27,'Bahamas');
Insert Into p_Pays (Idpays,NomPays) values (28,'Bhoutan');
Insert Into p_Pays (Idpays,NomPays) values (29,'Bouvet, Île');
Insert Into p_Pays (Idpays,NomPays) values (30,'Bélarus');
Insert Into p_Pays (Idpays,NomPays) values (31,'Belize');
Insert Into p_Pays (Idpays,NomPays) values (32,'Canada');
Insert Into p_Pays (Idpays,NomPays) values (33,'Cocos  (Keeling)');
Insert Into p_Pays (Idpays,NomPays) values (34,'Suisse');
Insert Into p_Pays (Idpays,NomPays) values (35,'Cook, Îles');
Insert Into p_Pays (Idpays,NomPays) values (36,'Chili');
Insert Into p_Pays (Idpays,NomPays) values (37,'Chine, République populaire de');
Insert Into p_Pays (Idpays,NomPays) values (38,'Colombie');
Insert Into p_Pays (Idpays,NomPays) values (39,'Costa Rica');
Insert Into p_Pays (Idpays,NomPays) values (40,'Serbie-et-Monténégro');
Insert Into p_Pays (Idpays,NomPays) values (41,'Cuba');
Insert Into p_Pays (Idpays,NomPays) values (42,'Christmas, Île');
Insert Into p_Pays (Idpays,NomPays) values (43,'Chypre');
Insert Into p_Pays (Idpays,NomPays) values (44,'Tchèque, République');
Insert Into p_Pays (Idpays,NomPays) values (45,'Allemagne');
Insert Into p_Pays (Idpays,NomPays) values (46,'Danemark');
Insert Into p_Pays (Idpays,NomPays) values (47,'Dominique');
Insert Into p_Pays (Idpays,NomPays) values (48,'Dominicaine République');
Insert Into p_Pays (Idpays,NomPays) values (49,'Équateur');
Insert Into p_Pays (Idpays,NomPays) values (50,'Estonie');
Insert Into p_Pays (Idpays,NomPays) values (51,'Espagne');
Insert Into p_Pays (Idpays,NomPays) values (52,'Finlande');
Insert Into p_Pays (Idpays,NomPays) values (53,'Fidji');
Insert Into p_Pays (Idpays,NomPays) values (54,'Falkland, Îles');
Insert Into p_Pays (Idpays,NomPays) values (55,'Micronésie, États fédérés de');
Insert Into p_Pays (Idpays,NomPays) values (56,'Îles Féroé');
Insert Into p_Pays (Idpays,NomPays) values (57,'Royaume-Uni');
Insert Into p_Pays (Idpays,NomPays) values (58,'Grenade');
Insert Into p_Pays (Idpays,NomPays) values (59,'Géorgie');
Insert Into p_Pays (Idpays,NomPays) values (60,'Gibraltar');
Insert Into p_Pays (Idpays,NomPays) values (61,'Groenland');
Insert Into p_Pays (Idpays,NomPays) values (62,'Grèce');
Insert Into p_Pays (Idpays,NomPays) values (64,'Guatemala');
Insert Into p_Pays (Idpays,NomPays) values (65,'Guam');
Insert Into p_Pays (Idpays,NomPays) values (66,'Guinée-Bissau');
Insert Into p_Pays (Idpays,NomPays) values (67,'Guyana');
Insert Into p_Pays (Idpays,NomPays) values (68,'Hong Kong');
Insert Into p_Pays (Idpays,NomPays) values (69,'Heard, Île et McDonald, Îles');
Insert Into p_Pays (Idpays,NomPays) values (70,'Honduras');
Insert Into p_Pays (Idpays,NomPays) values (71,'Croatie');
Insert Into p_Pays (Idpays,NomPays) values (72,'Haïti');
Insert Into p_Pays (Idpays,NomPays) values (73,'Hongrie');
Insert Into p_Pays (Idpays,NomPays) values (74,'Indonésie');
Insert Into p_Pays (Idpays,NomPays) values (75,'Irlande');
Insert Into p_Pays (Idpays,NomPays) values (76,'Israël');
Insert Into p_Pays (Idpays,NomPays) values (77,'Inde');
Insert Into p_Pays (Idpays,NomPays) values (78,'Archipel des Chagos');
Insert Into p_Pays (Idpays,NomPays) values (79,'Iraq');
Insert Into p_Pays (Idpays,NomPays) values (80,'Iran');
Insert Into p_Pays (Idpays,NomPays) values (81,'Islande');
Insert Into p_Pays (Idpays,NomPays) values (82,'Italie');
Insert Into p_Pays (Idpays,NomPays) values (83,'Jamaïque');
Insert Into p_Pays (Idpays,NomPays) values (84,'Jordanie');
Insert Into p_Pays (Idpays,NomPays) values (85,'Japon');
Insert Into p_Pays (Idpays,NomPays) values (86,'Kenya');
Insert Into p_Pays (Idpays,NomPays) values (87,'Kirghizistan');
Insert Into p_Pays (Idpays,NomPays) values (88,'Cambodge');
Insert Into p_Pays (Idpays,NomPays) values (89,'Kiribati');
Insert Into p_Pays (Idpays,NomPays) values (90,'Comores');
Insert Into p_Pays (Idpays,NomPays) values (91,'Saint-Kitts-et-Nevis');
Insert Into p_Pays (Idpays,NomPays) values (92,'Corée du nord');
Insert Into p_Pays (Idpays,NomPays) values (93,'Corée du sud');
Insert Into p_Pays (Idpays,NomPays) values (94,'Kuweït');
Insert Into p_Pays (Idpays,NomPays) values (95,'Caïmanes, Îles');
Insert Into p_Pays (Idpays,NomPays) values (96,'Kazakhstan');
Insert Into p_Pays (Idpays,NomPays) values (97,'Laos');
Insert Into p_Pays (Idpays,NomPays) values (98,'Liban');
Insert Into p_Pays (Idpays,NomPays) values (99,'Sainte-Lucie');
Insert Into p_Pays (Idpays,NomPays) values (100,'Liechtenstein');
Insert Into p_Pays (Idpays,NomPays) values (101,'Sri Lanka');
Insert Into p_Pays (Idpays,NomPays) values (102,'Libéria');
Insert Into p_Pays (Idpays,NomPays) values (103,'Lesotho');
Insert Into p_Pays (Idpays,NomPays) values (104,'Lituanie');
Insert Into p_Pays (Idpays,NomPays) values (105,'Luxembourg');
Insert Into p_Pays (Idpays,NomPays) values (106,'Lettonie');
Insert Into p_Pays (Idpays,NomPays) values (107,'Libyenne, Jamahiriya arabe');
Insert Into p_Pays (Idpays,NomPays) values (108,'Maroc');
Insert Into p_Pays (Idpays,NomPays) values (109,'Moldova, République de');
Insert Into p_Pays (Idpays,NomPays) values (110,'Madagascar');
Insert Into p_Pays (Idpays,NomPays) values (111,'Marshall, Îles');
Insert Into p_Pays (Idpays,NomPays) values (112,'Macédoine');
Insert Into p_Pays (Idpays,NomPays) values (113,'Mali');
Insert Into p_Pays (Idpays,NomPays) values (114,'Myanmar');
Insert Into p_Pays (Idpays,NomPays) values (115,'Mongolie');
Insert Into p_Pays (Idpays,NomPays) values (116,'Macao');
Insert Into p_Pays (Idpays,NomPays) values (117,'Mariannes du Nord, Îles');
Insert Into p_Pays (Idpays,NomPays) values (118,'Mauritanie');
Insert Into p_Pays (Idpays,NomPays) values (119,'Montserrat');
Insert Into p_Pays (Idpays,NomPays) values (120,'Malta');
Insert Into p_Pays (Idpays,NomPays) values (121,'Maurice');
Insert Into p_Pays (Idpays,NomPays) values (122,'Maldives');
Insert Into p_Pays (Idpays,NomPays) values (123,'Malawi');
Insert Into p_Pays (Idpays,NomPays) values (124,'Mexique');
Insert Into p_Pays (Idpays,NomPays) values (125,'Malaisie');
Insert Into p_Pays (Idpays,NomPays) values (126,'Mozambique');
Insert Into p_Pays (Idpays,NomPays) values (127,'Namibie');
Insert Into p_Pays (Idpays,NomPays) values (128,'Nouvelle-Calédonie');
Insert Into p_Pays (Idpays,NomPays) values (129,'Niger');
Insert Into p_Pays (Idpays,NomPays) values (130,'Norfolk, Île');
Insert Into p_Pays (Idpays,NomPays) values (131,'Nigéria');
Insert Into p_Pays (Idpays,NomPays) values (132,'Nicaragua');
Insert Into p_Pays (Idpays,NomPays) values (133,'Pays-Bas');
Insert Into p_Pays (Idpays,NomPays) values (134,'Norvège');
Insert Into p_Pays (Idpays,NomPays) values (135,'Népal');
Insert Into p_Pays (Idpays,NomPays) values (136,'Nauru');
Insert Into p_Pays (Idpays,NomPays) values (137,'Niue');
Insert Into p_Pays (Idpays,NomPays) values (138,'Nouvelle-Zélande');
Insert Into p_Pays (Idpays,NomPays) values (139,'Oman');
Insert Into p_Pays (Idpays,NomPays) values (140,'Panama');
Insert Into p_Pays (Idpays,NomPays) values (141,'Pérou');
Insert Into p_Pays (Idpays,NomPays) values (142,'Polynésie française');
Insert Into p_Pays (Idpays,NomPays) values (143,'Papouasie-Nouvelle-Guinée');
Insert Into p_Pays (Idpays,NomPays) values (144,'Philippines');
Insert Into p_Pays (Idpays,NomPays) values (145,'Pakistan');
Insert Into p_Pays (Idpays,NomPays) values (146,'Pologne');
Insert Into p_Pays (Idpays,NomPays) values (147,'Saint-Pierre-et-Miquelon');
Insert Into p_Pays (Idpays,NomPays) values (148,'Pitcairn');
Insert Into p_Pays (Idpays,NomPays) values (149,'Territoire palestinien occupé');
Insert Into p_Pays (Idpays,NomPays) values (150,'Portugal');
Insert Into p_Pays (Idpays,NomPays) values (151,'Palaos');
Insert Into p_Pays (Idpays,NomPays) values (152,'Paraguay');
Insert Into p_Pays (Idpays,NomPays) values (153,'Qatar');
Insert Into p_Pays (Idpays,NomPays) values (154,'Roumanie');
Insert Into p_Pays (Idpays,NomPays) values (155,'Russie, Fédération de');
Insert Into p_Pays (Idpays,NomPays) values (156,'Rwanda');
Insert Into p_Pays (Idpays,NomPays) values (157,'Arabie saoudite');
Insert Into p_Pays (Idpays,NomPays) values (158,'Salomon, Îles');
Insert Into p_Pays (Idpays,NomPays) values (159,'Seychelles');
Insert Into p_Pays (Idpays,NomPays) values (160,'Soudan');
Insert Into p_Pays (Idpays,NomPays) values (161,'Suède');
Insert Into p_Pays (Idpays,NomPays) values (162,'Singapour');
Insert Into p_Pays (Idpays,NomPays) values (163,'Sainte-Hélène');
Insert Into p_Pays (Idpays,NomPays) values (164,'Slovénie');
Insert Into p_Pays (Idpays,NomPays) values (165,'Slovaquie');
Insert Into p_Pays (Idpays,NomPays) values (166,'Sierra Leone');
Insert Into p_Pays (Idpays,NomPays) values (167,'Saint-Marin');
Insert Into p_Pays (Idpays,NomPays) values (168,'Sénégal');
Insert Into p_Pays (Idpays,NomPays) values (169,'Somalie');
Insert Into p_Pays (Idpays,NomPays) values (170,'Suriname');
Insert Into p_Pays (Idpays,NomPays) values (171,'Sao Tomé-et-Principe');
Insert Into p_Pays (Idpays,NomPays) values (172,'El Salvador');
Insert Into p_Pays (Idpays,NomPays) values (173,'Syrienne, République arabe');
Insert Into p_Pays (Idpays,NomPays) values (174,'Swaziland');
Insert Into p_Pays (Idpays,NomPays) values (175,'Turks et Caïques, Îles');
Insert Into p_Pays (Idpays,NomPays) values (176,'Tchad');
Insert Into p_Pays (Idpays,NomPays) values (177,'Terres australes françaises');
Insert Into p_Pays (Idpays,NomPays) values (178,'Togo');
Insert Into p_Pays (Idpays,NomPays) values (179,'Thaïlande');
Insert Into p_Pays (Idpays,NomPays) values (180,'Tadjikistan');
Insert Into p_Pays (Idpays,NomPays) values (181,'Tokelau');
Insert Into p_Pays (Idpays,NomPays) values (182,'Timor-Leste');
Insert Into p_Pays (Idpays,NomPays) values (183,'Turkménistan');
Insert Into p_Pays (Idpays,NomPays) values (184,'Tunisie');
Insert Into p_Pays (Idpays,NomPays) values (185,'Tonga');
Insert Into p_Pays (Idpays,NomPays) values (186,'Turquie');
Insert Into p_Pays (Idpays,NomPays) values (187,'Trinité-et-Tobago');
Insert Into p_Pays (Idpays,NomPays) values (188,'Tuvalu');
Insert Into p_Pays (Idpays,NomPays) values (189,'Taïwan');
Insert Into p_Pays (Idpays,NomPays) values (190,'Tanzanie, République unie de');
Insert Into p_Pays (Idpays,NomPays) values (191,'Ukraine');
Insert Into p_Pays (Idpays,NomPays) values (192,'Ouganda');
Insert Into p_Pays (Idpays,NomPays) values (194,'États-Uni');
Insert Into p_Pays (Idpays,NomPays) values (195,'Uruguay');
Insert Into p_Pays (Idpays,NomPays) values (196,'Ouzbékistan');
Insert Into p_Pays (Idpays,NomPays) values (197,'Saint-Siège');
Insert Into p_Pays (Idpays,NomPays) values (198,'Saint-Vincent-et-les Grenadines');
Insert Into p_Pays (Idpays,NomPays) values (199,'Venezuela');
Insert Into p_Pays (Idpays,NomPays) values (200,'Vierges britanniques, Îles');
Insert Into p_Pays (Idpays,NomPays) values (201,'Vierges des Etats-Unis, Îles');
Insert Into p_Pays (Idpays,NomPays) values (202,'Viêt Nam');
Insert Into p_Pays (Idpays,NomPays) values (203,'Vanuatu');
Insert Into p_Pays (Idpays,NomPays) values (204,'Wallis et Futuna');
Insert Into p_Pays (Idpays,NomPays) values (205,'Samoa');
Insert Into p_Pays (Idpays,NomPays) values (206,'Ceuta');
Insert Into p_Pays (Idpays,NomPays) values (207,'Melilla');
Insert Into p_Pays (Idpays,NomPays) values (208,'Yémen');
Insert Into p_Pays (Idpays,NomPays) values (209,'Mayotte');
Insert Into p_Pays (Idpays,NomPays) values (210,'Afrique du Sud');
Insert Into p_Pays (Idpays,NomPays) values (211,'Zambie');
Insert Into p_Pays (Idpays,NomPays) values (212,'Zimbabwe');

--P_Fonction
INSERT INTO P_Fonction (IdFonction,NomFonction) VALUES (1,'Administrateur');
INSERT INTO P_Fonction (IdFonction,NomFonction) VALUES (2,'Coach');
INSERT INTO P_Fonction (IdFonction,NomFonction) VALUES (3,'Client');

--P_Horraire
Insert into P_Horraire (IdBloc,IdHorraire,Horraire)  values  ('AM',1,'9:00');
Insert into P_Horraire (IdBloc,IdHorraire,Horraire)  values  ('AM',2,'9:20');
Insert into P_Horraire (IdBloc,IdHorraire,Horraire)  values  ('AM',3,'9:40');
Insert into P_Horraire (IdBloc,IdHorraire,Horraire)  values  ('AM',4,'10:00');
Insert into P_Horraire (IdBloc,IdHorraire,Horraire)  values  ('AM',5,'10:20');
Insert into P_Horraire (IdBloc,IdHorraire,Horraire)  values  ('AM',6,'10:40');
Insert into P_Horraire (IdBloc,IdHorraire,Horraire)  values  ('AM',7,'11:00');
Insert into P_Horraire (IdBloc,IdHorraire,Horraire)  values  ('AM',8,'11:20');
Insert into P_Horraire (IdBloc,IdHorraire,Horraire)  values  ('AM',9,'11:40');
Insert into P_Horraire (IdBloc,IdHorraire,Horraire)  values  ('AM',10,'12:00');
Insert into P_Horraire (IdBloc,IdHorraire,Horraire)  values  ('PM',11,'14:00');
Insert into P_Horraire (IdBloc,IdHorraire,Horraire)  values  ('PM',12,'14:20');
Insert into P_Horraire (IdBloc,IdHorraire,Horraire)  values  ('PM',13,'14:40');
Insert into P_Horraire (IdBloc,IdHorraire,Horraire)  values  ('PM',1,'15:00');
Insert into P_Horraire (IdBloc,IdHorraire,Horraire)  values  ('PM',2,'15:20');
Insert into P_Horraire (IdBloc,IdHorraire,Horraire)  values  ('PM',3,'15:40');
Insert into P_Horraire (IdBloc,IdHorraire,Horraire)  values  ('PM',4,'16:00');
Insert into P_Horraire (IdBloc,IdHorraire,Horraire)  values  ('PM',5,'16:20');
Insert into P_Horraire (IdBloc,IdHorraire,Horraire)  values  ('PM',6,'16:40');
Insert into P_Horraire (IdBloc,IdHorraire,Horraire)  values  ('PM',7,'17:00');
Insert into P_Horraire (IdBloc,IdHorraire,Horraire)  values  ('PM',8,'17:20');
Insert into P_Horraire (IdBloc,IdHorraire,Horraire)  values  ('PM',9,'17:40');
Insert into P_Horraire (IdBloc,IdHorraire,Horraire)  values  ('PM',10,'18:00');

--p_jour
INSERT INTO P_Jour (IdJour,NomJour) VALUES (  1,'Lundi');
INSERT INTO P_Jour (IdJour,NomJour) VALUES (  2,'Mardi');
INSERT INTO P_Jour (IdJour,NomJour) VALUES (  3,'Mercredi');
INSERT INTO P_Jour (IdJour,NomJour) VALUES (  4,'Jeudi');
INSERT INTO P_Jour (IdJour,NomJour) VALUES (  5,'Vendredi');
INSERT INTO P_Jour (IdJour,NomJour) VALUES (  6,'Samedi');
INSERT INTO P_Jour (IdJour,NomJour) VALUES (  7,'Dimanche');


--P_Salle
INSERT INTO P_Salle(IdSalle,NumSalle,NomSalle,TelSalle,MailSalle,IdContactCoach) VALUES(1,'G-001','Salle de sport Omnes','+33 01 33 33 44 55','salle.sport@omnessports.fr',0);
INSERT INTO P_Salle(IdSalle,NumSalle,NomSalle,TelSalle,MailSalle,IdContactCoach) VALUES(2,'G-010','Bureau','+33 01 23 45 67 89','',2);



